### ISSUE TITLE
utaumapのリンク切れ問題

### ISSUE THREAD

**Issue by Yumemigachi** [shinta0806/UtaYomi#63]
唄詠の音源検索ボタンを押すと飛ばされる、
http://www47.atpages.jp/utaumap/general/Loading.html?AppVer=Ver%207.62
がリンク切れとなっており、スパムサイトに飛ばされる問題があります。

修正案
UTAU音声ライブラリwiki
https://utau.wiki.fc2.com/wiki/%E9%9F%B3%E6%BA%90%E9%85%8D%E5%B8%83%E6%89%80%E4%B8%80%E8%A6%A7

にリンクを更新するのはいかがでしょうか

**Comment by shinta0806** [comment]
［対応状況］完了
［報告経路］コンタクト

**Comment by shinta0806** [comment]
唄詠 2 にて、リンク切れサイトへのリンクを廃止しました。
